---
title: "Grupo de Leitura Científica do Laboratório de Genética e Biologia Molecular (LGBM) Unisinos"
author: "Dra. Fernanda Rodrigues de Avila"
date: "2025-10-15"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{css echo = FALSE}
h1, h2, h3, h4, h5, h6 {
  color: #8b5e5e; /* Cor específica para os títulos */
}

strong {
  color: #bf4080; /* Cor específica para o texto em negrito */
}
```

Nesta página estarão disponíveis os artigos e materiais de apoio
didático das nossas discussões.

## 17/10/2025

-   Artigo: [Unravelling the cryptic diversity of the low-dispersal land
    planarian *Cephaloflexa bergi* to elucidate diversification
    processes in the Brazilian Atlantic
    Forest](17_10_25/Lorenzo&al_zlaf096.pdf)

-   Material de apoio: [Roteiro de Discussão de Artigo
    Científico](17_10_25/discussao_lorenzo_et_al_2025.html)

-   Gravação: [Vídeo da reunião (áudio com problema, captou apenas o
    microfone e não o som da
    chamada)](https://www.youtube.com/watch?v=sEtgm858CSg)

## 31/10/25

-   continuação da discussão de Lorenzo et al. 2025.

-   Gravação: [Vídeo da
    reunião](https://www.youtube.com/watch?v=tgja1JGHymw)

## 07/11/25

-   Não houve reunião por ausencia de quorum.

## 14/11/25

-   Finalizamos a discussão de Lorenzo et al. 2025.

-   Não foi realizada a gravação.

## 21/11/25

-   Não haverá reunião.

## 28/11/25

-   Não houve reunião por ausencia de quorum.

## Próxima reunião 05/12/25

***Excepcionalmente às 9h da manhã***

-   Livro: [Princípios de sistemática zoológica: material de apoio para
    o I CVSZ / Caroline Batistim Oswald (org.)... [ et al.] . 1ª ed. –
    Belo Horizonte : PGZoo UFMG,
    2020.](28_11_25/PrincipiosdeSistemticaZoolgica_CVSZooUFMG.pdf)

-   Capítulos para discussão: 1, 2 e 3

------------------------------------------------------------------------

**Lembrete: não existem perguntas bobas em ciência. Se algo não ficou
claro, provavelmente outros colegas têm a mesma dúvida.**

Dra. Fernanda Rodrigues de Avila

<https://avilaf.github.io/>

[fernandar.avila\@gmail.com](mailto:fernandar.avila@gmail.com){.email}
